[[signs]]
name="cute"
fsw='M518x545S2ff00482x483S1f540492x521S20500508x519'
swu='ğ ƒğ¤˜ğ¤³ñ‹¾¡ğ£´ğ£µñ…°¡ğ£¾ğ¤›ñ†‡¡ğ¤ğ¤™'
hns='î€€î€Œî€©î€¾îîƒ îƒ‘î°îƒ¡'

[[signs.definitions]]
text="cute, adorable, sweet"
pos="subs."

[[signs.definitions]]
text="aww"
pos = "excl."

#--------------------------------#
[[signs]]
name="drink-coffee"
fsw='M536x516S10640521x488S10651464x496S28902493x484'
swu='ğ ƒğ¤ªğ¤–ñ€Šğ¤›ğ£ºñ€Š’ğ£¢ğ¤‚ñ‰£ğ£¿ğ£¶'
hns='î€‚î€î€‘î€©î€¾îƒ­î‚†î‚º'

[[signs.definitions]]
text = "to drink coffee, to have a cup of coffee"
pos = "v.intr"

[[signs.definitions]]
text = "to serve sme. coffee, to pour sme. a coffee, to have coffee with sme."
pos = "v.tr"

#--------------------------------#
[[signs]]
name="private"
fsw='M521x514S36d00479x486S15001458x487'
swu = 'ğ ƒğ¤›ğ¤”ñ£¡ğ£±ğ£¸ñ¸‚ğ£œğ£¹'
hns='î€…î€‘î€Œî€§î€¸î™î’îƒ'

[[signs.definitions]]
text="private, personal"
pos = "subs."

[[signs.definitions]]
text="one's own (things, belongings, affairs)"
pos = "subs."

#--------------------------------#
[[signs]]
name="secret"
fsw='M518x533S33b00482x483S15000486x502'
swu='ğ ƒğ¤˜ğ¤§ñ˜¡ğ£´ğ£µñ¸ğ£¸ğ¤ˆ'
hns = 'î€…î€‘î€Œî€ î€¸îŠîƒ'
pos = "subs."

[[signs.definitions]]
text = "secret, hidden, confidential"
pos = "subs."

#--------------------------------#
[[signs]]
name="coffee"
fsw='M512x533S10640493x467S2a300489x497'
swu='ğ ƒğ¤’ğ¤§ñ€Šğ£¿ğ£¥ñ‰´¡ğ£»ğ¤ƒ'
hns='î€‚î€î€‘î€©î€¾î‚ªî€¨î€¼îƒ™'

[[signs.definitions]]
text="coffee"
pos = "subs."

#--------------------------------#
[[signs]]
name="leave"
fsw='M525x516S10e20476x486S2890a496x485'
swu='ğ ƒğ¤Ÿğ¤–ñ€•¡ğ£®ğ£¸ñ‰«ğ¤‚ğ£·'
hns='î€„î€î€ îƒ­î€¼î‚‚î‚º'

[[signs.definitions]]
text = "to leave, to go away"
pos = "v.intr"

[[signs.definitions]]
text = "goodbye, see ya"
pos = "excl."

#--------------------------------#
[[signs]]
name="tea"
fsw='M514x530S19640486x470S2a300491x494'
swu='ğ ƒğ¤”ğ¤¤ñƒ¢ğ£¸ğ£¨ñ‰´¡ğ£½ğ¤€'
hns='î€ˆî€î±î²î³î€©î€¾î‚ªî€¨î€¼îƒ™'

[[signs.definitions]]
text = "tea, tisane, beverage brewed by steeping leaves in hot water"
pos = "subs."

#--------------------------------#
[[signs]]
name="drink-tea"
fsw='M535x519S19640512x496S19651465x495S28902487x482'
swu='ğ ƒğ¤©ğ¤™ñƒ¢ğ¤’ğ¤‚ñƒ¢’ğ££ğ¤ñ‰£ğ£¹ğ£´'
hns='î€ˆî€î±î²î³î€©î€¾îƒ­î‚†î‚º'

[[signs.definitions]]
text = "to drink tea, to have a cup of tea"
pos = "v.intr"

[[signs.definitions]]
text = "to serve sme. tea, to pour sme. a cup of tea, to have tea with sme."
pos = "v.tr"

#--------------------------------#
[[signs]]
name="pee"
fsw='M516x531S14012485x469S25104498x498'
swu='ğ ƒğ¤–ğ¤¥ñ “ğ£·ğ£§ñ‡¹¥ğ¤„ğ¤„'
hns='î€„î²î€î¹î°î€¥î€ºîƒ î‚„î‚§îƒ¡'

[[signs.definitions]]
text = "to pee, to piss, to urinate"
pos = "v.intr"

#--------------------------------#
[[signs]]
name="poo"
fsw='M510x535S20350492x465S22a04493x485S15250490x504'
swu='ğ ƒğ¤ğ¤©ñ†…±ğ£¾ğ££ñ†¿…ğ£¿ğ£·ñ¼‘ğ£¼ğ¤Š'
hns='î€€î€î€©î€¼î‚„î€…î€î€î€©î€¼'

[[signs.definitions]]
text = "to poop, to go poo, to take a shit"
pos = "v.intr."

#--------------------------------#
[[signs]]
name="baby"
fsw='M521x516S36d00479x485S1703e464x485S20600456x505'
swu='ğ ƒğ¤›ğ¤–ñ£¡ğ£±ğ£·ñ‚¨¿ğ£¢ğ£·ñ†‰ğ£šğ¤‹'
hns='î€î€‘î€¦î€¸î™î‘îƒ‘îƒ˜'

[[signs.definitions]]
text = "baby, infant"
pos = "subs."

#--------------------------------#
[[signs]]
name="sushi"
fsw='M514x524S17131494x490S11557487x497S20800498x476'
swu='ğ ƒğ¤”ğ¤ñ‚ª’ğ¤€ğ£¼ñ€ ¸ğ£¹ğ¤ƒñ†Œğ¤„ğ£®'
hns='îƒ¢î€ƒî€î€ªî€¼îƒ§î€î€‘î€¨î€¸îƒ£îƒ‘îƒ¢î¸î±î²îƒ§î§îƒ£'

[[signs.definitions]]
text = "sushi"
pos = "subs."

#--------------------------------#
[[signs]]
name="time"
fsw='M536x520S1dc27513x490S2890a487x480S1eb10464x492'
swu='ğ ƒğ¤ªğ¤šñ…Š¨ğ¤“ğ£¼ñ‰«ğ£¹ğ£²ñ… ±ğ£¢ğ£¾'
hns='î€†î€ î€¾î‚‚î‚ºî€‚î€Œî€¡î€¼'

[[signs.definitions]]
text = "time, moment"
pos = "subs."

#--------------------------------#
[[signs]]
name="sleep"
fsw='M542x518S30007482x483S10e21512x477'
swu='ğ ƒğ¤°ğ¤˜ñŒ€ˆğ£´ğ£µñ€•¢ğ¤’ğ£¯'
hns='î€„î€î€§î€¼î‚î˜îƒ'

[[signs.definitions]]
text = "to sleep, to nap, to fall asleep"
pos = "v.intr."

#--------------------------------#
[[signs]]
name="sleepy"
fsw='M546x518S10e21516x482S30007482x483S31b30488x495S20600505x471'
swu='ğ ƒğ¤´ğ¤˜ñ€•¢ğ¤–ğ£´ñŒ€ˆğ£´ğ£µñŒ©‘ğ£ºğ¤ñ†‰ğ¤‹ğ£©'
hns='î€„î€î€§î€¼î‚î˜îƒ îƒ‘î±îƒ¡îƒ˜'

[[signs.definitions]]
text = "sleepy, tired, sleepiness, tiredness"
pos = "subs."

#--------------------------------#
[[signs]]
name="take_train"
fsw='M508x546S11000492x519S11030492x455S26600492x486'
swu='ğ ƒğ¤ğ¤´ñ€˜ğ£¾ğ¤™ñ€˜±ğ£¾ğ£™ñˆ™ğ£¾ğ£¸'
hns='î€„î€î€’î€ î€¸î‚‰î€„î€î€’î€©î€¸'

[[signs.definitions]]
text = "to take the train, to travel by train"
pos = "v.intr."

[[signs.definitions]]
text = "to go smwh. by train, to take the train to smwh."
pos = "v.tr."

#--------------------------------#
[[sign]]
name="train"
fsw='M514x525S11000492x498S26b00487x476'
swu='ğ ƒğ¤”ğ¤Ÿñ€˜ğ£¾ğ¤„ñˆ ¡ğ£¹ğ£®'
hns='î€„î€î€’îƒ î€ î€¸î‚ªî€©î€¸îƒ¡îƒ˜'

[[signs.definitions]]
text = "train, locomotive"
pos = "subs."

#--------------------------------#
[[sign]]
name="bad-taste"
fsw = 'M538x544S33b00482x483S12800493x511S2e200518x512'
swu='ğ ƒğ¤¬ğ¤²ñ˜¡ğ£´ğ£µñ€¼ğ£¿ğ¤‘ñ‹“ğ¤˜ğ¤’'

[[signs.definitions]]
text = "to taste bad, to have an unpleasant taste"
pos = "v.intr."

#--------------------------------#
[[sign]]
name="good-taste"
fsw='M536x526S33b00482x483S13d00507x511S22114504x503'
swu = 'ğ ƒğ¤ªğ¤ ñ˜¡ğ£´ğ£µñ›¡ğ¤ğ¤‘ñ†±µğ¤Šğ¤‰'

[[signs.definitions]]
text = "to taste good, to have a pleasant taste"
pos = "v.intr."

#--------------------------------#